Preview support
adobe/aem-test-samples pull request #39
Opened 2021-10-08 11:53 UTC by amit-jain

## Description

Support replication on the preview agent

## Related Issue

https://github.com/adobe/aem-test-samples/issues/38

## Motivation and Context

The support for preview agent will enable testing for the preview environments recently added

## How Has This Been Tested?

Changes tested on a cloud environment

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2021-10-08 11:54 UTC, amit-jain commented
Relies on changes in the PR - https://github.com/adobe/aem-testing-clients/pull/59

Is based on changes in https://github.com/adobe/aem-test-samples/pull/37

2021-10-08 11:57 UTC, amit-jain commented
@dulvac Appreciate your review

2021-10-26 12:52 UTC, dulvac requested changes

2021-10-26 12:52 UTC, dulvac commented on smoke/pom.xml
> +            <version>0.8.1-SNAPSHOT</version>
This needs to be a released version

2021-10-26 12:52 UTC, dulvac commented on smoke/src/main/java/com/adobe/cq/cloud/testing/it/smoke/PublishEndToEndIT.java
> +    public PublishRule publishRule = new PublishRule(root, cqBaseClassRule.authorRule, cqBaseClassRule.publishRule);
Please rename `PublishRule` to something that doesn't clash with `cqBaseClassRule.publishRule` and creates confusion. Like `ContentPublishingRule`

2021-11-09 15:18 UTC, amit-jain commented
@tmaret Could you please review

2021-11-15 11:18 UTC, dulvac approved these changes

2021-11-23 13:41 UTC, amit-jain commented
Merged all changes from PR #37. Also, needs merge and release of https://github.com/adobe/aem-testing-clients/pull/62 before this is merged

2021-11-25 08:34 UTC, amit-jain commented
@dulvac This issue is finally updated with the latest released version for aem-testing-clients and good to be merged. Thanks!!

2022-03-04 07:25 UTC, closed without merging