fixes #95 disable SearchIT
adobe/aem-test-samples pull request #96
Opened 2024-04-18 18:46 UTC by adamcin

resolves #95 by adding `@Ignore` to the SearchIT class.

## Description

Skip the SearchIT test for product 

## Related Issue

#95 

## Motivation and Context

SearchIT times out for customers with `nt:base` index definitions during CM pipeline Product Tests phase.

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-05-13 14:01 UTC, chibulcuteanu approved these changes

2024-05-14 08:24 UTC, andresbott approved these changes

2024-05-14 09:10 UTC, fabriziofortino approved these changes

2024-05-14 09:23 UTC, dulvac requested changes
I would go for deleting it instead

2024-05-14 09:47 UTC, chibulcuteanu commented
Let's close this one and focus on https://github.com/adobe/aem-test-samples/pull/98, which removes the test completely.

2024-05-14 10:01 UTC, dulvac commented
closing in favor of https://github.com/adobe/aem-test-samples/pull/98

2024-05-14 10:01 UTC, closed without merging